<?php

/**
 * @file
 * This module holds functions for module hero.
 * Please contribute!
 */

/*
 * Implements hook_theme()
 */
function module_heros_theme($existing, $type, $theme, $path) {

    return [
        'hero_list' => [
            'variables' => ['items' => [], 'title' => ''],
        ]
    ];
}
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter() on behalf of module_heros.module.
 */
function module_heros_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    // Change form id here

}
